# Generated by Django 4.0.5 on 2022-08-03 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ceb09fe-ccf1-4953-96a2-f5d3affef5f9'), primary_key=True, serialize=False, unique=True),
        ),
    ]
