# Generated by Django 4.0.5 on 2022-08-03 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5949e468-5687-499d-b266-1b34627d1522'), primary_key=True, serialize=False, unique=True),
        ),
    ]
