# Generated by Django 4.0.5 on 2022-07-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_account_groups_account_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_permissions',
        ),
    ]
