# Generated by Django 4.0.5 on 2022-07-18 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0003_alter_comment_id_alter_idea_id_alter_idea_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1db269b0-ebb8-4b04-8715-74e2592cf4f4'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b598a55e-2921-4f22-ad51-358559b54544'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('78db09cc-8e5c-4e91-b163-3e0a699a2fbe'), primary_key=True, serialize=False, unique=True),
        ),
    ]
