# Generated by Django 4.0.5 on 2022-07-18 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0005_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51338502-5e1a-433d-982a-a2880df80bc0'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('137d13e6-b665-4187-8969-c253fe69428b'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4ce17c2b-0450-45ea-ad8f-945ab195f23a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
