# Generated by Django 4.0.5 on 2022-07-28 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0011_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('680d99c1-8a1c-4ac3-8992-41eaacf82496'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('352595a6-b640-4235-8a5c-ce49faa66163'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c24dca14-a400-4acc-b67e-b502d506e71d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
