# Generated by Django 4.0.5 on 2022-08-03 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0012_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('684cea65-2aaf-47f5-9c2b-3ccf8042d3c2'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('085c6397-6d6c-4283-abf9-0d17182ba8cf'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0109c36a-701e-47ef-8dc7-f3ee269d5398'), primary_key=True, serialize=False, unique=True),
        ),
    ]
