# Generated by Django 4.0.5 on 2022-08-03 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0013_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9108606d-8c8a-41a5-bde3-ceccec718edb'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d5d6f09e-8fea-421c-90df-30bc59609d9e'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f0a43eea-780d-4412-9cb8-20ddf48a036a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
