# Generated by Django 4.0.5 on 2022-08-03 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0014_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14c0b2fd-6637-4431-aaf5-18f419ffbb47'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51a028e6-be5a-424f-9202-22540230083f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e1936c0b-671b-436e-88b3-09421d023685'), primary_key=True, serialize=False, unique=True),
        ),
    ]
