# Generated by Django 4.0.5 on 2022-08-03 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0015_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b4e9d02-9dd3-4e40-8565-a952b6387087'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5721ac85-3ef0-4101-8ba9-9a607a762b6e'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b358e720-9c2e-414d-a1a0-9a4b1bf8af1e'), primary_key=True, serialize=False, unique=True),
        ),
    ]
