# Generated by Django 4.0.5 on 2022-08-03 12:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0017_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63e6570f-7d9a-40ae-82b4-bf4b2126e206'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1cb8afa0-1591-4705-b654-80997eb0601d'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a4f96dad-8bcd-45de-b744-ecac0f5e83ef'), primary_key=True, serialize=False, unique=True),
        ),
    ]
