# Generated by Django 4.0.5 on 2022-08-03 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0018_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('04b19830-0edf-4a40-89d2-5f96ed3864fd'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a999c085-d730-42de-b0d8-360f7dd3ec29'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('012f22b6-ff34-4403-aedb-90a1f1584cec'), primary_key=True, serialize=False, unique=True),
        ),
    ]
