# Generated by Django 4.0.5 on 2022-08-03 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0019_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e4315c7e-d26d-4d61-b467-835cd1872f50'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e256137e-8c66-40a6-9961-575d05b197f2'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('755f31b4-df12-4f80-88b1-31782262f6d5'), primary_key=True, serialize=False, unique=True),
        ),
    ]
