# Generated by Django 4.0.5 on 2022-08-03 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0020_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bc370b86-186f-4486-a74d-d1dac672afd7'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9d7844de-bcb8-438b-ad61-4f69fcc7f650'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a8bfa520-1f78-4f3f-9210-21961e94169b'), primary_key=True, serialize=False, unique=True),
        ),
    ]
