# Generated by Django 4.0.5 on 2022-08-08 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0022_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2acc39aa-9b6b-4e14-a918-97d11a8c092a'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d34333dd-e38e-4037-bc82-38a302dd632f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f78f663-0648-4b43-b8dc-bc0e200eecc9'), primary_key=True, serialize=False, unique=True),
        ),
    ]
