# Generated by Django 4.1 on 2022-08-15 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0023_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b79d0786-ccde-4268-ab17-3aeb7d879e3f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1de9e58-63a8-4e52-85c9-ce10a57973d4'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('36f16769-e153-49b5-b95c-6296a3caec70'), primary_key=True, serialize=False, unique=True),
        ),
    ]
