# Generated by Django 4.1 on 2022-08-15 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0024_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('65ba2581-77e5-43cf-bc58-3d6e189f7115'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bff0b832-7463-4496-97b6-bd5e16831a6f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aecfa057-5b51-4f00-a90f-3af4524bb9d3'), primary_key=True, serialize=False, unique=True),
        ),
    ]
