# Generated by Django 4.1 on 2022-08-15 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0025_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c4d8bdf7-d356-49dc-b54c-80bc48f650be'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e1bd3da-ea1c-4fac-a420-4700ec01a87c'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b54c14b6-3662-475f-97a9-a38b4ab270b7'), primary_key=True, serialize=False, unique=True),
        ),
    ]
