# Generated by Django 4.1 on 2022-08-15 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0027_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c3cbf1fb-3d77-4823-9817-911ed839beba'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b986de1f-5775-46c9-ac83-469781d43c70'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('13f0eb3a-701a-4d26-9da4-38966af9df96'), primary_key=True, serialize=False, unique=True),
        ),
    ]
