# Generated by Django 4.1 on 2022-08-15 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0028_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d53975bd-3ea2-4f65-83d7-13aee90195b3'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cfc8b020-4dff-4c14-8949-565c9f565c6f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b227a920-3fab-40fd-8aa5-bf34ae8cd100'), primary_key=True, serialize=False, unique=True),
        ),
    ]
