# Generated by Django 4.1 on 2022-08-15 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0029_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80cffd61-91c6-4be6-a3e5-15f9be880426'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f889de0d-9974-4a93-874e-aa44ef2b9a42'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d31f29f1-5aaf-413a-b207-137265912fc0'), primary_key=True, serialize=False, unique=True),
        ),
    ]
