# Generated by Django 4.1 on 2022-08-15 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0030_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48d6ca06-352d-4ee0-9227-385e898fbf57'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('72be237a-b872-4c72-994f-b53ccc32321b'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fe6fc2bf-ef87-4442-ade8-2d15a31e096d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
