# Generated by Django 4.0.5 on 2022-07-03 22:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed77d5ad-7a6e-42bb-b178-b46f649a000c'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4ecd2e04-40b5-4521-84bd-0204d15e8e02'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dc508e17-a8e9-43e4-9fc5-dd240dbb2e14'), primary_key=True, serialize=False, unique=True),
        ),
    ]
