# Generated by Django 4.0.5 on 2022-07-18 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0004_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f9afb85b-e10a-422c-b8f0-26cf06afc7ac'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f626dbd0-7879-4413-935a-3a076a1c7b2d'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eec6c1c1-73ed-4198-8dd8-a38d1fda6290'), primary_key=True, serialize=False, unique=True),
        ),
    ]
