# Generated by Django 4.0.5 on 2022-07-18 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0006_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fffb84dc-37cc-4638-9448-3887970394fb'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8df2f33b-892a-46e2-b8b3-1fa96fbe3480'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('662911a2-d805-40d1-b9c2-7714623c5b91'), primary_key=True, serialize=False, unique=True),
        ),
    ]
