# Generated by Django 4.0.5 on 2022-07-18 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0007_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e8af8e1-9dd5-42b7-8e5a-1d700647636c'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c39086b3-ad8f-47d7-a205-9a781be73304'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('107180a3-f6ce-431a-9211-456a3c89c342'), primary_key=True, serialize=False, unique=True),
        ),
    ]
