# Generated by Django 4.0.5 on 2022-07-19 23:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_api', '0008_alter_comment_id_alter_idea_id_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2bd894a8-4383-4767-b139-c6b485ff625e'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3fd218bf-187d-488d-8039-0a80254e2299'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3a3f890d-556e-490c-acd4-19114417c0c2'), primary_key=True, serialize=False, unique=True),
        ),
    ]
